name: Deploy Production

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install firebase-tools
      # Note: we fix the version to avoid 12.6.2 which is broken
      - run: yarn global add firebase-tools@12.5.2

      # Install deps
      - run: yarn --frozen-lockfile

      # Create the env files
      - name: Create env files
        run: |
          echo "${{ secrets.ENV_FILE_PRODUCTION }}" > ./packages/app/.env.production
          echo "${{ secrets.ENV_FILE_PRODUCTION }}" > ./packages/functions/.env.production
          echo "${{ secrets.ENV_FILE_PRODUCTION }}" > ./packages/website/env/.env.production

      # Authenticate with Google Cloud for firebase
      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PRODUCTION }}'

      # Set the active project
      - run: yarn firebase:use production

      # Deploy production
      - run: yarn deploy:production

  deploy-sentry:
    needs: deploy
    runs-on: ubuntu-latest

    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

    steps:
      - uses: actions/checkout@v4

      # This is necessary for the Create Sentry release step
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      # Creates a Sentry release
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        with:
          version: ${{ steps.package-version.outputs.current-version}}
          environment: production
