name: Storybook

on:
  push:
    branches:
      - master
    paths:
      - stories/**
      - src/components/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # This is necessary for Chromatic to detect baseline commits
          fetch-depth: 0

      - run: cd ./packages/app && yarn --frozen-lockfile

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          buildScriptName: 'build:storybook'
          exitZeroOnChanges: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/app
